---

- name: Creates directory
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ destfile }}"
    - "{{ extfile }}"
  tags:
    - createfiles

- name: Install httpd, podman, httpd-tools, unzip, zip, tar
  yum:
    name: "{{ item }}"
    state: latest
    update_only: yes
  become: yes
  loop:
    - httpd
    - podman
    - httpd-tools
    - unzip
    - zip
    - tar
  tags:
    - packeges

- debug:
   msg: "{{ ansible_os_family }}"

- name: install yum module container-tools
  shell: yum module install -y container-tools:rhel8
  when: ansible_os_family == "Red Hat Enterprise Linux"
  tags:
    - yummodule

- name: install oc linux client linux x86_64 [oc,kubectl] 
  get_url: 
    url: https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/latest/openshift-client-linux.tar.gz
    dest: "{{ destfile }}"
  when: ansible_os_family == "Red Hat Enterprise Linux" or ansible_os_family == "Red Hat"
  tags:
    - occlient

- name: extract oc kubectl from tar.gz
  ansible.builtin.unarchive:
    src: "{{ destfile }}/openshift-client-linux.tar.gz"
    dest: "{{ extfile }}"
  when: ansible_os_family == "Red Hat Enterprise Linux" or ansible_os_family == "Red Hat"
  tags:
    - ocextract

- name: install opm linux x86_64 [opm]
  get_url: 
    url: https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/latest/opm-linux.tar.gz
    dest: "{{ destfile }}"
  when: ansible_os_family == "Red Hat Enterprise Linux" or ansible_os_family == "Red Hat"
  tags:
    - opmclient

- name: extract opm from tar.gz
  ansible.builtin.unarchive:
    src: "{{ destfile }}/opm-linux.tar.gz"
    dest: "{{ extfile }}"
  when: ansible_os_family == "Red Hat Enterprise Linux" or ansible_os_family == "Red Hat"
  tags:
    - opmextract

- name: install grpcurl 1.8.6 linux x86_64
  get_url:
    url: https://github.com/fullstorydev/grpcurl/releases/download/v1.8.6/grpcurl_1.8.6_linux_x86_64.tar.gz
    dest: "{{ destfile }}"
  when: ansible_os_family == "Red Hat Enterprise Linux" or ansible_os_family == "Red Hat"
  tags:
    - grpcrulinstall

- name: extract grpcurl 1.8.6 linux x86_64
  ansible.builtin.unarchive:
    src: "{{ destfile }}/grpcurl_1.8.6_linux_x86_64.tar.gz"
    dest: "{{ extfile }}"
  args:
    creates: /usr/local/sbin/grpcurl
  tags:
    -grpcurlextract

- name: copy opm oc kubectl grpcurl to /usr/local/bin
  copy:
    src: "{{ extfile }}/"
    dest: /usr/local/bin
  args:
    creates: /usr/local/sbin/{oc,opm,kubectl,hrpcurl}
  become: yes

